### ISSUE TITLE
Redis Cluster Client support

### ISSUE THREAD

**Issue by Ghilteras** [alovn/go-bloomfilter#3]
Hey guys, saw that the last commit is 1y ago, is this project still maintained? Is it possible to use the redis client against a Redis cluster or does it only work against single primary instances?

**Comment by alovn** [comment]
Redis Cluster is supported now, use the version v1.1.0.

sample code:
```
rdb := redis.NewClusterClient(&redis.ClusterOptions{
    Addrs: []string{
        "127.0.0.1:6371",
        "127.0.0.1:6372",
        "127.0.0.1:6373",
    },
    Password: "1234",
})
bloom := bloomfilter.NewRedisBloomFilter(rdb, "test", 1000000)
```
